### ISSUE TITLE
Your dist file is empty

### ISSUE THREAD

**Issue by redaxmedia** [pid/speakingurl#107]
Hello friend,

is this a special trick or why is `speakingurl.min.js` empty? I suggest to **automate** your release process and **ensure** that the minified version is working using Travis CI or whatever.

github.com: https://github.com/pid/speakingurl/blob/v14.0.0/speakingurl.min.js
cdnjs.com: https://cdnjs.cloudflare.com/ajax/libs/speakingurl/14.0.0/speakingurl.min.js

Best regards
Henry

**Comment by pid** [comment]
thanks a lot

v14.0.1 was released

>  ensure that the minified version is working 
I will work on it 👍

**Comment by redaxmedia** [comment]
You are welcome
