### ISSUE TITLE
please mention breaking changes in releases

### ISSUE THREAD

**Issue by barbalex** [pid/speakingurl#110]
Our app broke recently.

I tracked it down to speakingurl removing special characters like "!", "?". This caused conflicts in document titles in our case.

I have no idea when this change was introduced. I _think_ it must have been introduced recently because documents only began to disappear in the last few months (judging from what users tell me).

I made it a habit to check the release messages when updating a dependency that indicates a breaking change with it's version number.

Unfortunately speakingurl does not mention _what_ could break (for instance: https://github.com/pid/speakingurl/releases/tag/v14.0.0).

Or is there a different way to see what could break?

**Comment by simison** [comment]
Have you checked [CHANGELOG.md](https://github.com/pid/speakingurl/blob/master/CHANGELOG.md)?

**Comment by simison** [comment]
+1 for speakingurl improving on semver front.

**Comment by barbalex** [comment]
@simison thanks, I hadn't known that was a thing. Problem solved (although I do not see what could have caused our problems - but then we must have just not noticed them earlier I guess)
