### ISSUE TITLE
Clarify how to allow additional characters

### ISSUE THREAD

**Issue by niftylettuce** [pid/speakingurl#115]
I wanted to allow the extra character `/` (a forward slash).

I attempted to use `custom: [ '/' ]` however this did not work.

The only solution I found currently was `uric: true`, but that does not satisfy my requirements, since I only want to allow the `/` and not all other URI characters.

@pid how do we solve this?

**Comment by leocaseiro** [comment]
Hi @niftylettuce, you can use the `custom` parameter, like so:

```js
getSlug(text, {
    custom: {'/': '/'}
});
```

See example http://plnkr.co/edit/PKTPa5SWnoXiDoMWFHLW?p=preview

**Comment by pid** [comment]
@leocaseiro thanks for support
