### ISSUE TITLE
Expand contractions before slugging

### ISSUE THREAD

**Issue by passcod** [pid/speakingurl#117]
Related to #105, but a different approach. Instead of omitting apostrophes and creating possibly-confusing words like `wont` or `well`, instead _expand_ the contractions (opt-in?), thus creating `do-not`, `will-not`, `we-will`, etc.

From the readme, this example:

```js
slug = getSlug('Don\'t drink and drive', {
	    titleCase: true
	});
console.log(slug); // Output: Don-t-Drink-And-Drive
```

would instead be:

```js
slug = getSlug('Don\'t drink and drive', {
	    titleCase: true,
        expandContractions: true
	});
console.log(slug); // Output: Do-Not-Drink-And-Drive
```

The package [contractions](https://www.npmjs.com/package/contractions) can be used for English.

I think there might be some use for this in French as well, but not as useful nor common. I'm not familiar enough with other languages.

**Comment by pid** [comment]
I think the better approach is to use the contraction module as needed and then pass it on to SpeakingURL. I don't want to inflate SpeakingURL; the goal is to use it in the browser -- size matters.

**Comment by passcod** [comment]
I guess? But also, contractions add <1K to the minified+compressed size, while if one really wanted to get the size down, they'd remove all the languages they didn't need and save about 3-4K. But I understand the argument.

**Comment by pid** [comment]
> while if one really wanted to get the size down, they'd remove all the languages they didn't need and save about 3-4K. But I understand the argument.

You are right, but a module should do one thing right, and this feature would open multiple other tasks for other languages as well. So it's best, to use the `contractions` beforehand of `speakingurl`. Better make a new function and merge this two tasks.

So for now, I will close this request - sorry.
