### ISSUE TITLE
'ñ' characther for latin char map

### ISSUE THREAD

**Issue by ivandevp** [pid/speakingurl#118]
Is there a good reason for mapping `ñ` and `Ñ` to `n` and `N` characters. As far as I know crawlers recognize this special character.

**Comment by leocaseiro** [comment]
Nowadays crawlers recognize most of the characters, as you can see on Wikipedia. However, I believe that speakingurl by default returns characters from `a-z`, `A-Z`, `0-9`, `-` and `_`. Which means `ñ` is not included.

Eq:
https://en.wikipedia.org/wiki/Ç
https://en.wikipedia.org/wiki/Ñ
https://en.wikipedia.org/wiki/Í


However, if you would like to keep `Ñ` or any other character you wish, add into your custom rules and speakingurl will not replace it, like so.

```js
getSlug('Ñoñería', {
  custom: {
    'ñ': 'ñ'
  }
});
```
> It'll return `ñoñeria`

See: https://plnkr.co/edit/ughWmKXLqSGGnkYCi4aS?p=preview

**Comment by pid** [comment]
@ivandevp I think, you don't need SpeakingURL ;-)  So SpeakingURL is for the others who need transliteration of URLs.
