### ISSUE TITLE
Custom map works different

### ISSUE THREAD

**Issue by boldkhuu** [pid/speakingurl#47]
It seems default mapping replaces my custom maps.

``` javascript
getSlug('буу', { custom: { 'б': 'б', 'у': 'у' } });
// result: buu
// desired result: буу
```

I don't want to transliterate cyrillic letters.

**Comment by pid** [comment]
Thanks for contribution, please check if it works for you

**Comment by pid** [comment]
with v1.1.0 you can add the chars as array

```
getSlug('буу', {
    custom: ['б', 'у']
  });
```

**Comment by boldkhuu** [comment]
Cool. Thank you for your update.
