### ISSUE TITLE
Expose the character mappings

### ISSUE THREAD

**Issue by mgax** [pid/speakingurl#53]
To allow monkey-patching, until pull requests make it into a stable version.

**Comment by simi** [comment]
You can use `custom` option to pass custom mappings to `getSlug`. See [README](https://github.com/pid/speakingurl#getsluginput-options) for more options.

**Comment by pid** [comment]
@mgax is the 'custom' option sufficiently?
But to make it more flexible, we could add pre and post hooks. Any suggestions?

**Comment by mgax** [comment]
For my use case, I've done the unicode folding manually, before calling `getSlug`. I guess `custom` would accomplish the same thing.

**Comment by simi** [comment]
I think custom is enough for this usecase anyway.

**Comment by pid** [comment]
ok, then I will close this issue
