### ISSUE TITLE
Incorrect type checking when looking for Node/AMD

### ISSUE THREAD

**Issue by jdiprizio** [pid/speakingurl#62]
Line 1363 and 1369, you're comparing a typeof against the undefined property instead of 'undefined' as a string.

In a browser, module.exports check is therefore executed resulting in a ReferenceError exception.

**Comment by pid** [comment]
ohhh yeahh, this must happen after some refactoring and injecting undefined ```(function (root, undefined) ```
:+1: 
will release v5.0.1
