### ISSUE TITLE
Why international words being translated into their english equivalents?

### ISSUE THREAD

**Issue by Rotemy** [pid/speakingurl#67]
All major browsers support unicode urls so you can just leave the words as they are and not transform them into English.

If that's the case and you agree with me you can use my code in your project.

       var text = 'text in every language in the world';
       var XRegExp = require('xregexp');
       var slugRegEx = XRegExp('\\p{^L}+');
       XRegExp.replace(text, slugRegEx, '-').toLowerCase();

**Comment by pid** [comment]
Thanks for your contribution
speakingurl module has a specific usecase => transliteration 
If you don't have the requirement to do that, your code could be the way to go.
Because of the need to include the xregexp module, I think at the moment, that I won't include this. But will check it soon.
