### ISSUE TITLE
Support Enclosed Alphanumerics

### ISSUE THREAD

**Issue by stonio** [pid/speakingurl#77]
Support Unicode block **Enclosed Alphanumerics**.
See https://en.wikipedia.org/wiki/Enclosed_Alphanumerics

**Comment by pid** [comment]
please use this, to solve your issue:
```
custom: {
  '①': '1',
  '②': '2',
  '.....': '....'
}
```

With only one thumb-up, I think there is no need to add this to the module.

**Comment by simison** [comment]
@pid that :thumbsup: was from yourself ;-D 

+1 for not adding. It's such a rare symbol; better not to bloat library with it.

**Comment by pid** [comment]
@simison with my :thumbup: I wanted to support this request ;-) But I'm alone ;-)
