### ISSUE TITLE
Rebuild speakingurl in CFML language

### ISSUE THREAD

**Issue by kevindb** [pid/speakingurl#81]
speakingurl does a wonderful job of converting virtually any text into a readable and SEO friendly string, suitable for use in a URL. I'm looking forward to replacing various half-hearted attempts to create such URLs with speakingurl. Thank you for this library.

I would like to rebuild a copy of speakingurl in the ColdFusion (CFML) language. The code would be open source, and written in CFML cfscript, but based heavily on the logic in your library.

For my open source projects, I like to use the [LGPL](http://choosealicense.com/licenses/lgpl-2.1/) to promote further open source contributions to the library. I don't believe there is a legal conflict between your BSD3 license and LGPL 2.1. **Do you object to my using the LGPL license my derivation of speakingurl?**

I'm a big fan of letting people know about existing projects my work is based on, and I will do the same with this project. Examples: [jquery-load-json](https://github.com/kevindb/jquery-load-json/blob/master/CONTRIBUTORS.md) and [cf-mailchimp](https://github.com/kevindb/cf-mailchimp/blob/master/CONTRIBUTORS.md).

Thank you

**Comment by pid** [comment]
Hi, feel free to do it ;)
