### ISSUE TITLE
How To Add Georgian Language Support?

### ISSUE THREAD

**Issue by vdanelia** [pid/speakingurl#92]
Hello how to add Georgian Language in "Speakingurl"?

**Comment by pid** [comment]
https://en.m.wikipedia.org/wiki/Romanization_of_Georgian 
ISO 9984

The transliteration table has to be added to speakingurl

If you can send a pull request, we can quickly release a new version ;-) otherwise you have to wait, Eventually I can take a look into this at the weekend

**Comment by vdanelia** [comment]
Hello again... Thanks for the reply...
if you can show me the example how it is done, I'll try to do it by myself....... 
:+1:

**Comment by pid** [comment]
@vdanelia Take a look in lib/speakingurl.js

**Comment by vdanelia** [comment]
ok I found it... i'll add Georgian .... 
:)

**Comment by vdanelia** [comment]
:+1:

**Comment by redaxmedia** [comment]
I suggest to use the latest ISO and not to wait for @pid to respond. Just send the pull request.

@pid What about a playground / demo for contributors with a input and output field?

**Comment by vdanelia** [comment]
hello @redaxmedia  ... ISO 9984-(1996) is very strange standard, no one uses that, no one site or person... because it consists with non georgian symblos (characters)... so I'll do National system-(2002)..

**Comment by vdanelia** [comment]
I'm finishing it and will make pull request today or tomorrow... 👍

**Comment by redaxmedia** [comment]
You did something wrong, I commented the pull request.

**Comment by pid** [comment]
@redaxmedia please run "gulp" before you commit, this will beautify your files, runs the test, you added test? 😉 .... so the formating will be unique

**Comment by redaxmedia** [comment]
Well, it is not me - it is @vdanelia who sends the pull request ... I guess he does not know how to run gulp

**Comment by pid** [comment]
V12.0.0 is released, with Support for Georgian

**Comment by redaxmedia** [comment]
Great move! Thank you

**Comment by vdanelia** [comment]
Perfect...
Greatest Thanks
