### ISSUE TITLE
not translating arabic

### ISSUE THREAD

**Issue by sherifsaleh** [pid/speakingurl#99]
Hi Sascha,
Thank you for the great work, I wanted to keep Arabic strings not converted to latin chars 'transliteration', but keeping the slugging functions converting white spaces, special chars ...
is there is a way to turn it on/off ? or i have to pass custom map ?

**Comment by pid** [comment]
> or i have to pass custom map ?

Hi, yes, think it's the way to go. The question is, if you need speakingurl for this point; a normal regex should work without to add an npm module, but with speakingurl it's simpler of course ;-)
